services:

  nammongodb:
    image: mongo:latest
    container_name: nammongodb
    restart: unless-stopped

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}

    ports:
      - "27017:27017"

    volumes:
      - mongo-data:/data/db

    networks:
      - product-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mongosh --username ${MONGO_USERNAME} --password ${MONGO_PASSWORD} --authenticationDatabase admin --eval \"db.adminCommand('ping')\""
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


  product-api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: product-api
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      PORT: ${PORT}
      MONGO_URI: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@nammongodb:27017/productdb?authSource=admin

    depends_on:
      nammongodb:
        condition: service_healthy

    networks:
      - product-network

    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s


networks:
  product-network:
    driver: bridge


volumes:
  mongo-data: